# Generated by Django 5.1 on 2024-08-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga_de_futbol', '0002_clasificacion_alter_jugador_fecha_nacimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clasificacion',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
