# Generated by Django 5.1 on 2024-08-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga_de_futbol', '0003_delete_clasificacion_alter_jugador_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateTimeField(),
        ),
    ]
