# Generated by Django 5.1.1 on 2024-09-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga_de_futbol', '0004_alter_jugador_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='puntos',
            field=models.IntegerField(),
        ),
    ]
