# Generated by Django 5.1.1 on 2024-09-19 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liga_de_futbol', '0007_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='ParticipantesDeLaLiga',
        ),
    ]
